### ISSUE TITLE
Test and eliminate bugs in IE 7-9 [Need help]

### ISSUE THREAD

**Issue by betamos** [betamos/Better-Autocomplete#10]
I want BAC to work in IE 7-9, if this is fairly straightforward I want it done before the initial release. I don't have easy access to a Windows machine right now, but I will try my best to fix it myself.

If you feel that you can help out, it would be awesome. Just send me a pull request or a patch.

**Comment by betamos** [comment]
IE 9 and 8 are highest priority. IE7 support is not essential.

**Comment by bratanon** [comment]
I have tested the implementation with Linkit and BAC in IE7-9 and as far as I can see it works pretty well. 

(If this is fixed https://github.com/betamos/Better-Autocomplete/issues/11)

**Comment by betamos** [comment]
Thanks, did you find a solution for the cross origin JSON communication?

`$.support.cors = true;` didn't work for me :/

**Comment by bratanon** [comment]
jQuery.support.cors = true; // force cross-site scripting (as of jQuery 1.5)

Works perfect with IE7-9.. 

Insert before the ajax call in "fetchRemoteData"

**Comment by betamos** [comment]
I'm glad it worked but it cannot require to change the source code. Can you
move that line outside better-autocomplete.js and any callbacks? The optimal
solution would be to run that line in your local script file before
instantiating better autocomplete, since even jQuery won't deal with IE:s
XDomainRequest object. Is that possible? Use example.html to test.

**Comment by bratanon** [comment]
If I put the support.cors insude the $(document).ready function in example.html, its the same result. Works prefect.

**Comment by bratanon** [comment]
Hmm, its works when I run this in my apache-windows, but not in apache-ubuntu.

**Comment by bratanon** [comment]
Ah, Think I found it. 

Try using "dataType: 'jsonp'" in the ajax request. 

Then the support.cors is unnecessary.

**Comment by betamos** [comment]
Really strange with the Windows/Ubuntu Apache differences. Could there be something else that differs between the installations? Local domain name bugs?

**Comment by betamos** [comment]
JSONP is not as awesome as JSON so JSON will still be default. The integrating developer can simply override the [fetchRemoteData callback](http://betamos.se/better-autocomplete/symbols/callbacks.html#fetchRemoteData).

**Comment by bratanon** [comment]
Yes your right about that. Maybe just a little comment on this in the code so users will have easy access to this infomation?

**Comment by betamos** [comment]
Sure, but the $.support.cors is still a mystery to me, I would like some clarification so we can help IE users in the best possible way...

**Comment by betamos** [comment]
This thread fell off topic, so I created another issue for the cross origin stuff: #15

**Comment by betamos** [comment]
I consider this issue done since it is not specific and it's already tested in IE7+
