### ISSUE TITLE
array.indexOf is unsupported by IE7-8

### ISSUE THREAD

**Issue by bratanon** [betamos/Better-Autocomplete#11]
There is a simple way to deal with this. 

We can just add that method with prototype. 

``` javascript
  if (!Array.indexOf){
    Array.prototype.indexOf = function(obj) {
    for (var i = 0; i < this.length; i++) {
      if (this[i]==obj) {
        return i;
      }
    }
    return -1;
    }
  };
```

**Comment by betamos** [comment]
Anon, now you are very evil! Don't extend global objects within your plugin, then people will become mad! Like in Greece! Instead use [the best parts of your library](http://api.jquery.com/jQuery.inArray/).

Thanks Emil!

**Comment by bratanon** [comment]
Yeah, Sorry, I just discoverd the same thing, and that works better.

**Comment by bratanon** [comment]
if ($.inArray( event.keyCode, options.selectKeys ) >= 0) {
