### ISSUE TITLE
IE: Scrolling results bug

### ISSUE THREAD

**Issue by bratanon** [betamos/Better-Autocomplete#14]
When you click in the scrollbar in the search results, the result div is is disappearing.

IE versions 7-9

**Comment by betamos** [comment]
There is already a preventDefault() for clicks on the div. As usual with IE bugs, people have already found [work-arounds](http://stackoverflow.com/questions/2023779/clicking-on-a-divs-scroll-bar-fires-the-blur-event-in-i-e). I'll look into this a bit deeper when I'm at my Windows machine.

**Comment by betamos** [comment]
Why do my intuition tell me that people who use IE are more likely to click in the scrollbar than other users? :D
