### ISSUE TITLE
IE: Cross domain requests

### ISSUE THREAD

**Issue by betamos** [betamos/Better-Autocomplete#15]
Cross domain requests has really been a hassle. Now I think I've found the solution. Since JSON and cross domain requests behave really strange on IE, I've now 1. added an option "crossOrigin" to BAC and 2. if this option is enabled _and_ jQuery.support.cors is false (like in IE) _then_ switch transfer method to JSONP instead. This works great with example.html on both local and remote resources. The discussion started in #10 btw...

**Comment by betamos** [comment]
Tested on IE9 in native, IE8 and IE7 mode. Works great.

**Comment by jakubwolny** [comment]
Also Opera does not have CORS support:
http://en.wikipedia.org/wiki/Cross-Origin_Resource_Sharing
