### ISSUE TITLE
Sort Problem

### ISSUE THREAD

**Issue by fredrickelango** [betamos/Better-Autocomplete#24]
the Value which I select 1st remains on the top for ever...
http://york.bncollege.com/webapp/wcs/stores/servlet/BNCBHomePage?storeId=32551&catalogId=10001&langId=-1

click on Department inputfield

**Comment by betamos** [comment]
I can't find that field, is it still there or can you show me how to recreate the problem?

It sounds like you haven't used a select callback properly. It is the integrating developers responsibility to decide what happens when an item is selected. You could e.g. focus another field or post a form.
