### ISSUE TITLE
Pressing [Return/Enter] on selection doesn't populate the text box

### ISSUE THREAD

**Issue by gorakhargosh** [betamos/Better-Autocomplete#8]
When trying to pick a suggestion from the dropdown menu, pressing the `[Return/Enter]` key
does not populate the text box. This issue has been observed on:
- Firefox Nightly 7.0a1 (2011-06-26)
- Chromium 14.0.802.0 (90236)
- Chrome 14.0.803.0 canary
- Chrome 14.0.797.0 dev
- Webkit Nightly Safari Version 5.0.5 (6533.21.1, r89772)
- Opera Next 11.50
- Opera Swordfish RC 4
- Camino Version 2.1a2pre (1.9.2.18pre 20110520001916)

All of these are running on Mac OS X 10.6.8

**Comment by gorakhargosh** [comment]
### Procedure:
1. Type something in the text box.
2. Suggestion dropdown shows up.
3. Use the arrow keys to select an item and press `[Return/Enter]` on the keyboard.

### Expected behavior:

The text box should be populated with the selected item
and a function should be called with the associated value.

### Observed behavior:

The text box is not populated with the selected item.

**Comment by betamos** [comment]
That is a feature. It is up to the integrating developer to define what happens when a selection is made, through the [select callback](http://betamos.se/better-autocomplete/symbols/callbacks.html#select). In example.html there is a demo of where it is inserted (phone numbers).

**Comment by gorakhargosh** [comment]
Oh. Well, most people will be expecting this out-of-the-box. =)

**Comment by betamos** [comment]
That may be true. I'm leaving this issue open for a while, for time to consider it :)

**Comment by gorakhargosh** [comment]
I like the way you've written your code. Probably one of the cleanest jQuery plugin I've seen so far. =)

**Comment by betamos** [comment]
Thank you very much. I intend to make this plugin usable for as many purposes as possible.

To the issue: I think you are right, and that the default behavior should be to insert the title into the input field. I will commit this now.

**Comment by gorakhargosh** [comment]
Awesome. =)
