### ISSUE TITLE
[Feature request] Clear button (&times;) in the input field.

### ISSUE THREAD

**Issue by gorakhargosh** [betamos/Better-Autocomplete#9]
This is a UX design request:

When typing stuff on a mobile phone or touchscreen devices, 
it may become hard to select text in order to clear the text box 
in some use cases. An explicit "clear" button comes in handy
when using such a device. 

For an example of what I mean by the "clear" button, you can
have a look at:

http://documentcloud.github.com/visualsearch/

The search field has a "x" button to clear the field. This helps 
with touch screen input.

Cheers!
Khargosh. =)

**Comment by betamos** [comment]
The native solution is to use [HTML5 Search input field](http://diveintohtml5.org/forms.html#type-search), and that would be preferred. Currently I don't think Better Autocomplete works on other than input type="text" fields, which it of course should... But I think the little "cross" should come from the browser's native support for it.
